GETTING_STARTED_URL="https://luelista.github.io/pre_workbench/getting-started"
SYNTAX_REFERENCE_URL="https://luelista.github.io/pre_workbench/syntax-reference"
KEY_BINDINGS_URL="https://luelista.github.io/pre_workbench/key-bindings"
ISSUE_TRACKER_URL="https://github.com/luelista/pre_workbench/issues"
MACRO_CODE_HELP_URL="https://luelista.github.io/pre_workbench/extending#macro-code-help"
MACRO_PROPERTIES_HELP_URL="https://luelista.github.io/pre_workbench/extending#macro-properties-help"
WEBSITE_URL="https://luelista.github.io/pre_workbench"
ERROR_REPORT_URL="https://dl.weller-it.com/pre_workbench/ping.php"
UPDATE_CHECK_URL="https://pypi.org/pypi/pre_workbench/json"
LOGFILE_NAME="pre_workbench.log"
INT32_MIN = -2**31
INT32_MAX = 2**31-1